name: issue pre-defined github context
on:
    issues:
        types:
            - opened
            - edited
            - closed
jobs:
    Info:
        runs-on: ubuntu-latest
        steps:
            - name: Info about the event type Issues
              run: echo "${{ toJson(github.event.issue) }}"
        